### ISSUE TITLE
HungerGame Arenas Does not load correctly.

### ISSUE THREAD

**Issue by xXSirGamesXx** [InfinityGamers/HungerGames#44]
build version 16, MCPE: 1.0.4.11, and For server software I'm using Genisys
After I created an arena following the steps that the video does I try joining the arena where the issue occurs. The server will just keep you on one of the slots I created but that's all it does. The game never starts. And /hg leave doesn't work either, just crashes server. That's the issue. I'll get the arena config in a minute.

```yaml
---
sign_line_1: '&6-=&e[&fS&cG&e]&6=-'
sign_line_2: '&f{on}&f/&a{max}'
sign_line_3: '&aGame: &f{game}'
sign_line_4: '&eStatus: {status}'
is_sky_wars: "no"
min_players: 2
max_players: 12
game_seconds: 2400.000000
waiting_seconds: 10.000000
game_level: hg
refill_chest_after_seconds: 200.000000
chest_items:
- 272 0 1
- 298 0 1
- 299 0 1
- 300 0 1
- 301 0 1
lobby_pos:
  x: 127.000000
  "y": 4.000000
  z: 128.000000
  level: world
death_match_pos:
  x: 140.000000
  "y": 4.000000
  z: 150.000000
  level: world
slots:
  1:
    x: 37.544700
    "y": 148.000000
    z: 86.388200
  2:
    x: 42.535700
    "y": 148.000000
    z: 57.634000
  3:
    x: 37.487200
    "y": 148.000000
    z: 28.362600
  4:
    x: 19.645100
    "y": 148.000000
    z: 7.608700
  5:
    x: -7.732600
    "y": 148.000000
    z: -0.590900
  6:
    x: -34.289400
    "y": 148.000000
    z: 7.477200
  7:
    x: -52.692900
    "y": 148.000000
    z: 28.274100
  9:
    x: -57.671900
    "y": 148.000000
    z: 57.184200
  8:
    x: -52.611100
    "y": 148.000000
    z: 86.409700
  10:
    x: -34.698500
    "y": 148.000000
    z: 107.312800
  11:
    x: -7.374500
    "y": 148.000000
    z: 115.714400
  12:
    x: 19.435700
    "y": 148.000000
    z: 107.585000
sign_list:
  -30:79:-117:spawn: ""
...
```
