### ISSUE TITLE
 client crash

### ISSUE THREAD

**Issue by llronaldoll** [InfinityGamers/HungerGames#83]
### Build Version
- 19.3

### PocketMine API Version
- 3.1.4

### Steps to reproduce

after some actions randomly the client closes alone during the game!

### Arena Config
```
---
sign_line_1: '&6-=&e[&fS&cG&e]&6=-'
sign_line_2: '&f{on}&f/&a{max}'
sign_line_3: '&aJogo: &f{game}'
sign_line_4: '&eStatus: {status}'
is_sky_wars: "no"
clear_inventory_on_join: true
min_players: 2
max_players: 8
game_seconds: 300.000000
waiting_seconds: 10.000000
game_level: Area51
refill_chest_after_seconds: 150.000000
chest_items:
- 272 0 1
- 298 0 1
- 299 0 1
- 300 0 1
- 301 0 1
lobby_pos:
  level: Midgard
  x: 343.557100
  "y": 45.000000
  z: 1206.271500
death_match_pos:
  x: 343.000000
  "y": 45.000000
  z: 1206.000000
  level: Midgard
slots:
  1:
    x: 1410.729600
    "y": 17.000000
    z: 929.220700
  2:
    x: 1415.224500
    "y": 17.000000
    z: 928.039600
  3:
    x: 1415.128800
    "y": 17.000000
    z: 922.750800
  4:
    x: 1411.006100
    "y": 17.000000
    z: 922.630100
sign_list:
  340:45:1248:Midgard: ""
...
```
